#!/bin/sh

airflow initdb
airflow webserver -p 8080 2>&1 > /airflow/logs/webserver.log &
airflow scheduler 2>&1 > /airflow/logs/scheduler/scheduler.log &
mlflow ui -h 0.0.0.0 2>&1 > /airflow/logs/mlflow.log &
